/* Version: 5.3.0 */
/* Show all data types */
drop table if exists test.demo_data_types;
create table test.demo_data_types(
    bit_col bit(64),
    tinyint_col tinyint,
    smallint_col smallint,
    mediumint_col mediumint,
    int_col int,
    bigint_col bigint,
    float_col float,
    double_col double,
    decimal_col decimal,
    decimal_83_col decimal(8,3),
    boolean_col boolean,
    date_col date,
    time_col time(6),
    datetime_col datetime(6),
    timestamp_col timestamp(6),
    year_col year,
    varchar_col varchar(16383),
    char_col varchar(30),
    binary_col binary(30),
    varbinary_col varbinary(30),
    tinyblob_col tinyblob,
    mediumblob_col mediumblob,
    blob_col blob,
    longblob_col longblob,
    tinytext_col tinytext,
    mediumtext_col mediumtext,
    text_col text,
    longtext_col longtext,
    enum_col enum('e1', 'e2', 'e3'),
    set_col set('e1', 'e2', 'e3'),
    json_col json /* experimental */
);

insert into test.demo_data_types values (
    b'10101',
    1,
    2,
    3,
    4,
    5,
    1.0,
    2.0,
    10,
    20.7,
    true,
    '2000-10-31',
    '12:12:12.123456',
    '2000-10-31 12:12:12.123456',
    '2000-10-31 12:12:12.123456',
    '2000',
    'VARCHAR',
    'CHAR',
    0xf1,
    0xf2,
    0xf3,
    0xf4,
    0xf5,
    0xf6,
    'TINYTEXT',
    'MEDIUMTEXT',
    'TEXT',
    'LONGTEXT',
    'e2',
    'e2,e3',
    '{"id":100, "name":"bgl"}'
);

select * from test.demo_data_types\G 
